### ISSUE TITLE
GUI crashes when using acquisition board with new FPGA module - check gateware version

### ISSUE THREAD

**Issue by LaurensGoyvaerts98** [open-ephys/acquisition-board#22]
At every step in the software the open ephys just crashes, while the green lights keep flickering. When trying to find the board, it crashes, then if by miracle it finds it, it will not find the headstage or it will crash again finding it. Then if you are patient enough to get to this step, it crashes during the impedance measurements or it makes just weird measurements.

**Comment by jsiegle** [comment]
We're very sorry to hear you're having trouble getting your acquisition board to work. We'd love to know more details about your setup, because this experience seems to be unique. Have you tried connecting to the board from multiple computers? That will help us determine if there's an issue with your acquisition board, or possibly something specific about the PC you're using.

If you can send a message to `support@oeps.tech`, we'd be happy to help you troubleshoot further.

**Comment by jonnew** [comment]
This is the wrong repo for this issue. Please submit an new issue to this repo since the acquisition board can be used with either the Open Ephys ECP5 FPGA module or an Opal Kelly board:

https://github.com/open-ephys/ECP5U85-BSE-USB

Also, the issue title "New FPGA open ephys is trash" and the issue itself contains numerous grammatical errors. It seems like it was typed hastily.  Once situated in the new repo, I suggest the title "This FPGA module is trash", which makes more sense. Also you can use free online tools for checking your grammar before you submit your issue.

**Comment by LaurensGoyvaerts98** [comment]
Ofcourse it was typed hastily, these issues with your fpga have cost me 6 hours to run 1 impedance measurement. If i did not need to invest that much time in simple things, I would have loved to type a more grammatically sound issue for you. Now, focus on the important things please…

**Comment by ChucklesOnGitHub** [comment]
We did remote troubleshooting with the user at OEPS Support.
- Gateware on user's board was v0.2. Update to v1.0 fixed the crashes.
- Gateware update procedure was not straightforward due to connection issues. User tried on different PCs and cables. Red power light on the FPGA module flickered. Blowing inside the USB connector seemed to work. 
- We went over the limitations of the inbuilt impedance measurement function of the Intan RHD2000 series chips.

Takeaways: 
- Always use the [latest gateware](https://open-ephys.github.io/acq-board-docs/User-Manual/Gateware-Update.html).
- Always check the USB3 connection and the power supply before attempting the gateware update procedure.

Please note I have updated the issue title to keep interactions within our community respectful. This issue is closed.

**Comment by LaurensGoyvaerts98** [comment]
Please note that the crashes are not over, they are just less frequent. The opal kelly fpga still works faster and more smoothly.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Ceci ***@***.***>
Verzonden: woensdag 26 juli 2023 20:41
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [open-ephys/acquisition-board] GUI crashes when using acquisition board with new FPGA module - check gateware version (Issue #22)


We did remote troubleshooting with the user at OEPS Support.

  *   Gateware on user's board was v0.2. Update to v1.0 fixed the crashes.
  *   Gateware update procedure was not straightforward due to connection issues. User tried on different PCs and cables. Red power light on the FPGA module flickered. Blowing inside the USB connector seemed to work.
  *   We went over the limitations of the inbuilt impedance measurement function of the Intan RHD2000 series chips.

Takeaways:

  *   Always use the latest gateware<https://open-ephys.github.io/acq-board-docs/User-Manual/Gateware-Update.html>.
  *   Always check the USB3 connection and the power supply before attempting the gateware update procedure.

Please note I have updated the issue title to keep interactions within our community respectful. This issue is closed.

**Comment by ChucklesOnGitHub** [comment]
Oh, I wasn't aware this was the case. Crashes can be related to software or hardware components other than the FPGA module. 

Since you continue to experience issues, please write to our support channel with the complete content of the GUI console, the session activity log file and a full description of the issue (what happens right before a crash, what frequency of crashes you are experiencing, what do you mean by saying the fpga is slow, etc). A screenshot of the issue can also help.

Once we narrow it down,  we can open a more specific issue in the appropriate repository. 

Unfortunately, the Opal Kelly FPGA module used in past versions of our acquisition board is no longer available. We documented the differences between both devices [here](https://open-ephys.github.io/acq-board-docs/User-Manual/New-FPGA.html#differences-with-previous-boards), and continue to improve the functionality of the new version thanks to user feedback.

**Comment by LaurensGoyvaerts98** [comment]
About the impedance measurement: Is there anywhere where I can read about the intan chip using a capacitor as a current source? Is there any manual about how the open ephys does the impedance measurement? Does it measure versus the ground or the reference when desoldering the 0-Ohm resistor on the Intan headstage board?

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Ceci ***@***.***>
Verzonden: donderdag 27 juli 2023 11:46
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [open-ephys/acquisition-board] GUI crashes when using acquisition board with new FPGA module - check gateware version (Issue #22)


Oh, I wasn't aware this was the case. Crashes can be related to software or hardware components other than the FPGA module.

Since you continue to experience issues, please write to our support channel with the complete content of the GUI console, the session activity log file and a full description of the issue (what happens right before a crash, what frequency of crashes you are experiencing, what do you mean by saying the fpga is slow, etc). A screenshot of the issue can also help.

Once we narrow it down, we can open a more specific issue in the appropriate repository.

Unfortunately, the Opal Kelly FPGA module used in past versions of our acquisition board is no longer available. We documented the differences between both devices here<https://open-ephys.github.io/acq-board-docs/User-Manual/New-FPGA.html#differences-with-previous-boards>, and continue to improve the functionality of the new version thanks to user feedback.

**Comment by ChucklesOnGitHub** [comment]
[Here](https://intantech.com/files/Intan_RHD2000_series_datasheet.pdf) is the Intan RHD2000 series chip datasheet.

The implementation of the impedance measurement procedure is not described in our user manuals, but the source code for the GUI Rhythm plugin and for the hardware are open. I'll reach out to the engineering team to see if they can provide further details on this. Are there any specific details you are looking for? Please note that part of our team is on holiday so their response might be delayed.

**Comment by LaurensGoyvaerts98** [comment]
I was looking for it myself, but I did not seem to find it. Thanks a lot for your help!
For the impedance measurement, normally a sine wave with a specific amplitude is applied against a counter and/or reference electrode. This depends if a two or three electrode setup is used. I am thus also wondering if the impedance is measured against the ground or reference or both, because you can also desolder the 0 Ohm resistor on the intan board.



Van: Ceci ***@***.***>
Verzonden: donderdag 27 juli 2023 13:43
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [open-ephys/acquisition-board] GUI crashes when using acquisition board with new FPGA module - check gateware version (Issue #22)


Here<https://intantech.com/files/Intan_RHD2000_series_datasheet.pdf> is the Intan RHD2000 series chip datasheet.

The implementation of the impedance measurement procedure is not described in our user manuals, but the source code for the GUI Rhythm plugin and for the hardware are open. I'll reach out to the engineering team to see if they can provide further details on this. Are there any specific details you are looking for? Please note that part of our team is on holiday so their response might be delayed.

**Comment by LaurensGoyvaerts98** [comment]
I was also wondering how the bandpass filter frequencies of the plugin are different than the frequencies you can select on the OE FPGA Acquisition board. Do they do the same? Or can you select a greater bandwidth on the acquisition board and then make it smaller with the Bandpass filter frequencies to distinguish a high pass or low pass?

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Ceci ***@***.***>
Verzonden: donderdag 27 juli 2023 13:43
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [open-ephys/acquisition-board] GUI crashes when using acquisition board with new FPGA module - check gateware version (Issue #22)


Here<https://intantech.com/files/Intan_RHD2000_series_datasheet.pdf> is the Intan RHD2000 series chip datasheet.

The implementation of the impedance measurement procedure is not described in our user manuals, but the source code for the GUI Rhythm plugin and for the hardware are open. I'll reach out to the engineering team to see if they can provide further details on this. Are there any specific details you are looking for? Please note that part of our team is on holiday so their response might be delayed.

**Comment by sneakers-the-rat** [comment]
> Wtf is this bullshit.

incredible open source decorum

**Comment by jonnew** [comment]
On the plus side, we finally adopted some reasonable community guidelines for Open Ephys:

https://openhardware.space/guidelines/

So, in the future an issue like this will be closed immediately and a two-strikes and you're out warning provided to the OP. @LaurensGoyvaerts98, this is your first strike. If you continue to have issues with hardware or software, create an issue in the relevant repo with a clear explanation of the problem and what precipitated it. Issues are developer tools, not a place for personal support. If you want to ask specific questions, discord is the best place for that. Please don't cross post. Obviously our guidelines apply there as well, so be civil.
